import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SideNavBar from "./component/SideNavBar";
import {NavigationContainer} from "@react-navigation/native";
import Recherche from "./component/Recherche";
import Welcome from "./component/Welcome";
import MinorCube from "./component/MinorCube";

const Badges: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MinorCube />
        </div>
    )
}

export default Badges;
