import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MinorCube from './component/MinorCube'

const TestThree: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <script
          src='https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js'
          integrity='sha512-yNJzAsg5JyP91u+sLHlUDULMBd3hmEiVkYeeN1cQBKaLZ7EyT6oH2u5THNIRM2Fu6VKcZJv+F/QAp1h/qzy9Ow=='
          crossOrigin='anonymous'
        ></script>
        <script src='https://cdn.jsdelivr.net/gh/mrdoob/three.js@master/examples/js/loaders/OBJLoader.js'></script>
        <script src='https://cdn.jsdelivr.net/gh/mrdoob/three.js@master/examples/js/loaders/MTLLoader.js'></script>
        <script src='https://cdn.jsdelivr.net/gh/mrdoob/three.js@master/examples/js/loaders/FontLoader.js'></script>
        <script src='https://cdn.jsdelivr.net/npm/drag-controls@1.0.4/dist/drag-controls.min.js'></script>
        <script src='https://cdn.jsdelivr.net/npm/three.interaction@0.2.3/build/three.interaction.js'></script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/tween.js/18.6.4/tween.umd.js'></script>
        {/* <script type='module' src='/js/script.js'></script> */}
        <script type='module' src='/js/temp.js'></script>
      </Head>
    </div>
  )
}

export default TestThree
